name: ft-transcendence

version: "3"
services:
  rproxy:
    image: caddy:2.11
    restart: always
    networks:
      - www
      - ws
      - storage
    ports:
      - "8000:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    env_file: .env
  www:
    image: oven/bun:1.3.5-debian
    working_dir: /app
    command: sh -c "bun ci && bun sv:prepare && ./container-entrypoint.sh bun dev"
    restart: always
    depends_on:
      - db
      - storage
    networks:
      - www
      - db
      - storage
    volumes:
      - ./www:/app
    env_file: .env
    healthcheck:
      test: ["CMD", "bun", "-e", "\"console.log(await fetch('${ORIGIN}'));\""]
      start_period: 30s
      start_interval: 5s
  drizzle:
    image: oven/bun:1.3.5-debian
    working_dir: /app
    command: bun db:studio --host=0.0.0.0
    restart: always
    depends_on:
      db:
        condition: service_started
      www:
        condition: service_healthy
    networks:
      - db
    volumes:
      - ./www:/app
    env_file: .env
    ports:
      - "4983:4983"
  ws:
    image: oven/bun:1.3.5-debian
    working_dir: /app
    command: bun run:ws
    restart: always
    depends_on:
      www:
        condition: service_healthy
      db:
        condition: service_started
      storage:
        condition: service_started
    networks:
      - ws
      - db
      - storage
    volumes:
      - ./www:/app
    env_file: .env
  db:
    image: postgres:18
    restart: always
    networks:
      - db
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql
  storage:
    image: ft-transcendence_garage
    build:
      context: .
      dockerfile: ./garage/Containerfile
    restart: always
    networks:
      - storage
    ports:
    - 3900:3900
    - 3902:3902
    volumes:
      - ./garage/config.toml:/etc/garage.toml:ro
      - ./garage/container-entrypoint.sh:/bin/entrypoint.sh:ro
      - storage-meta:/var/lib/garage/meta
      - storage-data:/var/lib/garage/data
    env_file: .env

volumes:
  db-data:
  storage-meta:
  storage-data:

networks:
  www:
    driver: bridge
  ws:
    driver: bridge
  db:
    driver: bridge
  storage:
    driver: bridge
