name: ft-transcendence

version: "3"
services:
  rproxy:
    image: caddy:2.11
    restart: always
    networks:
      - www
      - ws
      - storage
    ports:
      - "8000:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
  www:
    image: oven/bun:1.3.5-debian
    working_dir: /app
    command: sh -c "bun ci && bun sv:prepare && ./container-entrypoint.sh bun dev"
    restart: always
    depends_on:
      - db
      - storage
    networks:
      - www
      - db
      - storage
    volumes:
      - ./www:/app
      - api-keys:/tmp/api-keys:ro
    # env_file: ./www/.env
    environment:
      DATABASE_URL: postgres://root:mysecretpassword@db:5432/local
    ports:
      - "8080:8000"
  drizzle:
    image: oven/bun:1.3.5-debian
    working_dir: /app
    command: bun db:studio --host=0.0.0.0
    restart: always
    depends_on:
      - db
      - www
    networks:
      - db
    volumes:
      - ./www:/app
    # env_file: ./www/.env
    environment:
      DATABASE_URL: postgres://root:mysecretpassword@db:5432/local
    ports:
      - "4983:4983"
  db-seed:
    image: oven/bun:1.3.5-debian
    working_dir: /app
    command: bun db:seed
    depends_on:
      - db
      - www
    networks:
      - db
    volumes:
      - ./www:/app
    # env_file: ./www/.env
    environment:
      DATABASE_URL: postgres://root:mysecretpassword@db:5432/local
  ws:
    image: oven/bun:1.3.5-debian
    working_dir: /app
    command: bun run:ws
    restart: always
    depends_on:
      - db
    networks:
      - ws
      - db
    volumes:
      - ./www:/app
    # env_file: ./www/.env
    environment:
      DATABASE_URL: postgres://root:mysecretpassword@db:5432/local
  db:
    image: postgres:18
    restart: always
    networks:
      - db
    ports:
      - 5432:5432
    # env_file: ./db/.env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready"]
  storage:
    image: ft-transcendence_garage
    build:
      context: ./garage
      dockerfile: Containerfile
    restart: always
    networks:
      - storage
    ports:
    - 3900:3900
    - 3902:3902
    volumes:
      - ./garage/config.toml:/etc/garage.toml:ro
      - storage-meta:/var/lib/garage/meta
      - storage-data:/var/lib/garage/data
      - api-keys:/tmp/api-keys
    healthcheck:
      test: ["CMD", "garage", "status"]

volumes:
  db-data:
  storage-meta:
  storage-data:
  api-keys:

networks:
  www:
    driver: bridge
  ws:
    driver: bridge
  db:
    driver: bridge
  storage:
    driver: bridge
