import { drizzle } from "npm:drizzle-orm@^0.45.1/node-postgres";
import pg from "npm:pg@^8.13.1";
import * as table from "./src/lib/server/db/schema.ts";

const { Pool } = pg;

const pool = new Pool({
	connectionString: Deno.env.get("DATABASE_URL") || 
		"postgres://root:mysecretpassword@localhost:5432/local",
});

const db = drizzle(pool);

const pets = [
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Marguerite",
		species: "Vache",
		breed: "Holstein",
		age: "5 ans",
		description: "Vache douce et calme, adore les caresses. Parfaite pour les familles.",
		photo: "https://media.4-paws.org/4/9/8/9/49896113ec1edb7553e53df93fec214bfba35e4d/VIER%20PFOTEN_2015-04-27_010-3369x2246-3246x2246-1920x1329.jpg",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Pompom",
		species: "Lapin",
		breed: "Bélier",
		age: "2 ans",
		description: "Petit lapin affectueux avec de grandes oreilles tombantes.",
		photo: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Réglisse",
		species: "Chèvre",
		breed: "Naine",
		age: "3 ans",
		description: "Chèvre joueuse et curieuse, s'entend bien avec les enfants.",
		photo: "https://images.unsplash.com/photo-1553949285-f8a95d569d3b?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Caramel",
		species: "Poney",
		breed: "Shetland",
		age: "8 ans",
		description: "Poney doux et patient, idéal pour l'équitation des enfants.",
		photo: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Coquette",
		species: "Poule",
		breed: "Sussex",
		age: "1 an",
		description: "Poule pondeuse très productive, calme et docile.",
		photo: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Hercule",
		species: "Âne",
		breed: "Âne commun",
		age: "12 ans",
		description: "Âne gentil et travailleur, excellent gardien du troupeau.",
		photo: "https://binette-et-jardin.ouest-france.fr/images/dossiers/2017-12/ane-1-120401.jpg",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Flocon",
		species: "Mouton",
		breed: "Ouessant",
		age: "4 ans",
		description: "Petit mouton rustique avec une belle laine blanche.",
		photo: "https://images.unsplash.com/photo-1584276927340-8c4e238b5b71?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Roussette",
		species: "Vache",
		breed: "Jersiaise",
		age: "6 ans",
		description: "Vache laitière de race jersiaise, lait très riche en matières grasses.",
		photo: "https://media.4-paws.org/4/9/8/9/49896113ec1edb7553e53df93fec214bfba35e4d/VIER%20PFOTEN_2015-04-27_010-3369x2246-3246x2246-1920x1329.jpg",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Cannelle",
		species: "Chèvre",
		breed: "Alpine",
		age: "2 ans",
		description: "Chèvre alpine énergique, excellente productrice de lait.",
		photo: "https://lemagdesanimaux.ouest-france.fr/images/dossiers/2021-05/mini/elever-chevre-063237-650-400.jpg",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Plume",
		species: "Oie",
		breed: "Oie de Toulouse",
		age: "3 ans",
		description: "Grande oie imposante mais très gentille avec ses familiers.",
		photo: "https://www.ecomusee-rennes-metropole.fr/app/uploads/2020/10/oie-normande-scaled.jpg",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Noisette",
		species: "Lapin",
		breed: "Géant des Flandres",
		age: "3 ans",
		description: "Grand lapin au caractère doux, adore être brossé.",
		photo: "https://images.unsplash.com/photo-1535241749838-299277b6305f?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Belle",
		species: "Poney",
		breed: "Welsh",
		age: "10 ans",
		description: "Ponette expérimentée, parfaite pour l'apprentissage de l'équitation.",
		photo: "https://images.unsplash.com/photo-1551884831-bbf3cdc6469e?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Cocotte",
		species: "Poule",
		breed: "Rousse",
		age: "2 ans",
		description: "Poule rousse pondeuse, très sociable avec les autres animaux.",
		photo: "https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Cacahuète",
		species: "Cochon",
		breed: "Vietnamien",
		age: "4 ans",
		description: "Petit cochon vietnamien affectueux et très propre.",
		photo: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Diabolo",
		species: "Chèvre",
		breed: "Angora",
		age: "5 ans",
		description: "Chèvre angora avec une magnifique toison soyeuse.",
		photo: "https://lemagdesanimaux.ouest-france.fr/images/dossiers/2021-05/mini/elever-chevre-063237-650-400.jpg",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Pépite",
		species: "Poule",
		breed: "Marans",
		age: "1 an",
		description: "Poule marans aux œufs extra-roux, caractère vif et curieux.",
		photo: "https://images.unsplash.com/photo-1563281577-a7be47e20db9?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Tonnerre",
		species: "Cheval",
		breed: "Percheron",
		age: "9 ans",
		description: "Cheval de trait puissant mais au tempérament calme.",
		photo: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Gribouille",
		species: "Lapin",
		breed: "Nain Angora",
		age: "1 an",
		description: "Petit lapin angora avec un pelage exceptionnellement doux.",
		photo: "https://images.unsplash.com/photo-1535241749838-299277b6305f?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Neige",
		species: "Mouton",
		breed: "Mérinos",
		age: "3 ans",
		description: "Mouton mérinos avec une laine de qualité exceptionnelle.",
		photo: "https://images.unsplash.com/photo-1568476992901-cd0010eb2a9f?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Praline",
		species: "Vache",
		breed: "Limousine",
		age: "7 ans",
		description: "Vache limousine rustique et robuste, excellente mère.",
		photo: "https://media.4-paws.org/4/9/8/9/49896113ec1edb7553e53df93fec214bfba35e4d/VIER%20PFOTEN_2015-04-27_010-3369x2246-3246x2246-1920x1329.jpg",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Hector",
		species: "Canard",
		breed: "Coureur Indien",
		age: "2 ans",
		description: "Canard coureur très actif, excellent pour contrôler les nuisibles.",
		photo: "https://images.unsplash.com/photo-1551879400-0c0e84e90f0e?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Perle",
		species: "Oie",
		breed: "Blanche",
		age: "4 ans",
		description: "Oie blanche élégante, bonne gardienne de la ferme.",
		photo: "https://www.ecomusee-rennes-metropole.fr/app/uploads/2020/10/oie-normande-scaled.jpg",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Biscuit",
		species: "Cochon",
		breed: "Pot-Bellied",
		age: "3 ans",
		description: "Cochon miniature intelligent et affectueux.",
		photo: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Capucine",
		species: "Poule",
		breed: "Soie",
		age: "2 ans",
		description: "Poule d'ornement au plumage duveteux unique.",
		photo: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Éclair",
		species: "Poney",
		breed: "Connemara",
		age: "6 ans",
		description: "Poney sportif et endurant, parfait pour le saut d'obstacles.",
		photo: "https://images.unsplash.com/photo-1551884831-bbf3cdc6469e?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Miel",
		species: "Chèvre",
		breed: "Poitevine",
		age: "4 ans",
		description: "Chèvre au caractère doux, excellente laitière.",
		photo: "https://lemagdesanimaux.ouest-france.fr/images/dossiers/2021-05/mini/elever-chevre-063237-650-400.jpg",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Rouquin",
		species: "Âne",
		breed: "Miniature",
		age: "5 ans",
		description: "Petit âne roux très attachant et joueur.",
		photo: "https://binette-et-jardin.ouest-france.fr/images/dossiers/2017-12/ane-1-120401.jpg",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Bambou",
		species: "Lapin",
		breed: "Rex",
		age: "2 ans",
		description: "Lapin rex au pelage velouté exceptionnel.",
		photo: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=800",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Violette",
		species: "Vache",
		breed: "Aubrac",
		age: "5 ans",
		description: "Vache aubrac rustique, très adaptée aux terrains difficiles.",
		photo: "https://media.4-paws.org/4/9/8/9/49896113ec1edb7553e53df93fec214bfba35e4d/VIER%20PFOTEN_2015-04-27_010-3369x2246-3246x2246-1920x1329.jpg",
	},
	{
		id: crypto.randomUUID(),
		ownerId: crypto.randomUUID(),
		name: "Grisou",
		species: "Mouton",
		breed: "Suffolk",
		age: "4 ans",
		description: "Mouton suffolk robuste, bonne production de viande.",
		photo: "https://images.unsplash.com/photo-1584276927340-8c4e238b5b71?w=800",
	},
];

console.log("🌾 Peuplement de la base de données avec des animaux de la ferme...\n");

for (const pet of pets) {
	await db.insert(table.pet).values(pet);
	console.log(`✅ Ajouté : ${pet.name} (${pet.species} - ${pet.breed})`);
}

console.log(`\n🎉 ${pets.length} animaux ajoutés avec succès !`);
await pool.end();
Deno.exit(0);
